### ISSUE TITLE
导入时报错

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [ZZZure/ZZZeroUID#21]
日志如下
```Python
 2024-10-13 02:41:33.131 | ERROR    | gsuid_core.server:load_plugins:124 - 加载插件时发生错误: f-string: unmatched '(' (__init__.py, line 21)
Traceback (most recent call last):

  File "C:\Users\YuYue\Desktop\gsuid-core\gsuid_core\core.py", line 15, in <module>
    from gsuid_core.gss import gss  # noqa: E402

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "C:\Users\YuYue\Desktop\gsuid-core\gsuid_core\gss.py", line 10, in <module>
    gss.load_plugins()
    │   └ <function GsServer.load_plugins at 0x0000027725548F70>
    └ <gsuid_core.server.GsServer object at 0x0000027721B21BA0>

> File "C:\Users\YuYue\Desktop\gsuid-core\gsuid_core\server.py", line 94, in load_plugins
    self.load_dir_plugins(path, True)
    │    │                └ WindowsPath('C:/Users/YuYue/Desktop/gsuid-core/gsuid_core/plugins/ZZZeroUID/ZZZeroUID')
    │    └ <function GsServer.load_dir_plugins at 0x0000027725549000>
    └ <gsuid_core.server.GsServer object at 0x0000027721B21BA0>

  File "C:\Users\YuYue\Desktop\gsuid-core\gsuid_core\server.py", line 147, in load_dir_plugins
    importlib.import_module(f'{_p}')
    │         └ <function import_module at 0x0000027721054CA0>
    └ <module 'importlib' from 'C:\\Users\\YuYue\\AppData\\Local\\Programs\\Python\\Python310\\lib\\importlib\\__init__.py'>

  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           │          │           │    │        │        └ 0
           │          │           │    │        └ None
           │          │           │    └ 0
           │          │           └ 'plugins.ZZZeroUID.ZZZeroUID.zzzerouid_help'
           │          └ <function _gcd_import at 0x0000027720863490>
           └ <module '_frozen_importlib' (frozen)>

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "C:\Users\YuYue\Desktop\gsuid-core\gsuid_core\plugins\ZZZeroUID\ZZZeroUID\zzzerouid_help\__init__.py", line 21
    f'{get_plugin_available_prefix('ZZZeroUID')}帮助',
                                    ^^^^^^^^^

SyntaxError: f-string: unmatched '('
10-13 02:41:33 [WARNING] gsuid_core.server | 插件ZZZeroUID加载失败
```

**Comment by KimigaiiWuyi** [comment]
更新后检查

**Comment by YuYue-Amatsuki** [comment]
> 更新后检查

已解决
